// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9hcoM3q5CGlRqS0nZqdvlvviJeTXJAM',
    appId: '1:521280725475:web:2ac7b9c7ece3af56a380d6',
    messagingSenderId: '521280725475',
    projectId: 'kitchen-ai-app-finalyear',
    authDomain: 'kitchen-ai-app-finalyear.firebaseapp.com',
    storageBucket: 'kitchen-ai-app-finalyear.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7PMZ-ltcOExKfN_HHQhsEuoNnCSKQyBQ',
    appId: '1:521280725475:android:6a265e1d36c81ec5a380d6',
    messagingSenderId: '521280725475',
    projectId: 'kitchen-ai-app-finalyear',
    storageBucket: 'kitchen-ai-app-finalyear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6iFMH82QmXqJg9Hq0ZIqSWRVkt660wU',
    appId: '1:521280725475:ios:4b4debb3612ae426a380d6',
    messagingSenderId: '521280725475',
    projectId: 'kitchen-ai-app-finalyear',
    storageBucket: 'kitchen-ai-app-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.kitchenInventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6iFMH82QmXqJg9Hq0ZIqSWRVkt660wU',
    appId: '1:521280725475:ios:4b4debb3612ae426a380d6',
    messagingSenderId: '521280725475',
    projectId: 'kitchen-ai-app-finalyear',
    storageBucket: 'kitchen-ai-app-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.kitchenInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA9hcoM3q5CGlRqS0nZqdvlvviJeTXJAM',
    appId: '1:521280725475:web:6af5c2afe710f191a380d6',
    messagingSenderId: '521280725475',
    projectId: 'kitchen-ai-app-finalyear',
    authDomain: 'kitchen-ai-app-finalyear.firebaseapp.com',
    storageBucket: 'kitchen-ai-app-finalyear.firebasestorage.app',
  );
}
